name: Build and Deploy React App with LFTP

on:
  push:
    branches:
      - main # Trigger the deployment on the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # You can adjust this if needed

      # Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Upload the build directory as an artifact (optional)
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: build/ # Assuming build directory is 'build'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Install LFTP
      - name: Install LFTP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp

      # Deploy using LFTP
      - name: Deploy via LFTP
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "mirror -R -P 4 ./build /; quit" ${{ secrets.FTP_SERVER }}
